#!/bin/sh

# reset aliases to ensure that they don't break
unalias -a

# change the term name for elinks if needed
case "$TERM" in
    screen-256color) alias elinks="TERM=xterm-256color elinks" ;;
esac

# use ~/.config/x11/xinitrc
alias \
    startx="startx $XINITRC"

# neovim familiarity
alias \
    nvim="nvim" \
    vim="nvim" \
    vimdiff="nvim -d"

# ls options
alias \
    ls="ls --group-directories-first --color=auto -ChN" \
    la="ls -A" \
    l.="ls -d .*" \
    l1="ls -1" \
    l1a="ls -1A" \
    l1.="ls -d .* -1" \
    ll="ls -l" \
    lla="ls -lA" \
    ll.="ls -d .* -l" \
    l="ls"

# shortcuts
alias \
    e="$EDITOR" \
    g="git" \
    cl="clear" \
    cdd="cd /" \
    ..="cd ../" \
    c-="cd -" \
    reboot="sudo reboot" \
    poweroff="sudo poweroff"

# package management shortcuts
alias \
    xi="sudo xbps-install" \
    xq="xbps-query" \
    xr="sudo xbps-remove -R"

# verbosity and confirmation
alias \
    cp="cp -iv" \
    mv="mv -iv" \
    rm="rm -Iv" \
    mkdir="mkdir -v" \
    chmod="chmod -v" \
    chown="chown -v" \
    ln="ln -v" \
    pkill="pkill -e"

# add color to commands
alias \
    dir="dir --color=auto" \
    vdir="vdir --color=auto" \
    grep="grep --color=auto" \
    fgrep="rgrep --color=auto" \
    egrep="egrep --color=auto" \
    diff="diff --color=auto"

# yt-dlp options
# also see ${HOME}/.config/yt-dlp, these are just for different presets
alias \
    yt="yt-dlp --config-locations \"${XDG_CONFIG_HOME:-$HOME/.config}/yt-dlp/video-config\"" \
    yta="yt-dlp --config-locations \"${XDG_CONFIG_HOME:-$HOME/.config}/yt-dlp/audio-config\"" \
    ytc="yt --config-locations \"${XDG_CONFIG_HOME:-$HOME/.config}/yt-dlp/video-config\" --concat-playlist always" \
    ytca="yt --config-locations \"${XDG_CONFIG_HOME:-$HOME/.config}/yt-dlp/audio-config\" --concat-playlist always"
