#!/bin/bash

# if our session isn't a login shell, source ~/.config/shell/profile
case "$0" in
    -*) ;;
     *) [ -r "${XDG_CONFIG_HOME:-$HOME/.config}/shell/profile" ] && . ${XDG_CONFIG_HOME:-$HOME/.config}/shell/profile ;;
esac

# check if the proper shell is sourcing this file
case "$SHNAME" in
    bash) ;;
       *) . "$ENV"; return 0 ;;
esac

# if not running interactively, don't do anything else
case "$-" in
    *i*) ;;
      *) return 0 ;;
esac

# bash settings
shopt -s checkwinsize
shopt -s cmdhist
shopt -s histappend
shopt -s huponexit
shopt -s xpg_echo

# if we have access to the 'stty' binary, specify args for it
[ -n "$(command -v stty)" ] && stty -ixon

# enable vi editing mode
set -o vi

# run set_ps1 before PS1 is printed (thereby setting it)
export PROMPT_COMMAND="export PS1=\"\$(print-prompt)\""

# load ~/.config/shell/aliases
[ -r "${XDG_CONFIG_HOME:-$HOME/.config}/shell/aliases" ] && . ${XDG_CONFIG_HOME:-$HOME/.config}/shell/aliases
