#!/bin/sh

# if our session isn't a login shell, source ~/.config/shell/profile
case "$0" in
    -*) ;;
     *) [ -r "${XDG_CONFIG_HOME:-$HOME/.config}/shell/profile" ] && . ${XDG_CONFIG_HOME:-$HOME/.config}/shell/profile ;;
esac

# if not running interactively, don't do anything else
case "$-" in
    *i*) ;;
      *) return 0 ;;
esac

# POSIX-compliant shells don't support prompt expansion, but we can
# do this ourselves by executing this function anywhere necessary
set_ps1() {
    export PS1="$(print-prompt)"
}

# if we have access to the 'stty' binary, specify args for it
[ -n "$(command -v stty)" ] && stty -ixon

# enable vi editing mode
set -o vi

# set the prompt
set_ps1

# change the behavior of cd, pushd, popd, and git to run the 'set_ps1' function
# normal shells don't support running a prompt command, but this emulates that behavior
for i in cd pushd popd git; do
    eval "$i() { command $i \$@; set_ps1; }"
done

# load ~/.config/shell/aliases
[ -r "${XDG_CONFIG_HOME:-$HOME/.config}/shell/aliases" ] && . ${XDG_CONFIG_HOME:-$HOME/.config}/shell/aliases
