#!/bin/sh

# load the X resource file
[ -r "$HOME/.themes/Xresources" ] && {
    exec xrdb $HOME/.themes/Xresources &
}

# set the wallpaper
[ -r "$HOME/.wallpapers/bg" ] && {
    exec hsetroot -fill $HOME/.wallpapers/bg &
}

# wallpaper & compositor
[ -r "${XDG_CONFIG_HOME:-$HOME/.config}/picom/picom.conf" ] && {
    exec picom -b --config "${XDG_CONFIG_HOME:-$HOME/.config}/picom/picom.conf" &
}

# run dwm commands
[ "$WM_USE" = "dwm" ] && {
    exec dwmblocks &
    exec dbus-launch --exit-with-session dwm
    exit
}

# invalid wm_use at this point
[ -n "$WM_USE" ] && {
    printf "\n${0##*/}: error: No startup rule for $WM_USE\n\n"
} || {
    printf "\n${0##*/}: error: No WM_USE specified\n\n"
}
