local M = {}

function M.set(col16, col30)
    return {
        ["@annotation"]             = { fg = col16.color0F },
        ["@attribute"]              = { fg = col16.color0A },
        ["@character"]              = { fg = col16.color08 },
        ["@constructor"]            = { fg = col16.color0C },
        ["@constant"]               = { fg = col16.color08 },
        ["@constant.builtin"]       = { fg = col16.color09 },
        ["@constant.macro"]         = { fg = col16.color08 },
        ["@error"]                  = { fg = col16.color08 },
        ["@exception"]              = { fg = col16.color08 },
        ["@float"]                  = { fg = col16.color09 },
        ["@keyword"]                = { fg = col16.color0E },
        ["@keyword.function"]       = { fg = col16.color0E },
        ["@keyword.return"]         = { fg = col16.color0E },
        ["@function"]               = { fg = col16.color0D },
        ["@function.builtin"]       = { fg = col16.color0D },
        ["@function.macro"]         = { fg = col16.color08 },
        ["@function.call"]          = { fg = col16.color0D },
        ["@operator"]               = { fg = col16.color05 },
        ["@keyword.operator"]       = { fg = col16.color0E },
        ["@method"]                 = { fg = col16.color0D },
        ["@method.call"]            = { fg = col16.color0D },
        ["@namespace"]              = { fg = col16.color08 },
        ["@none"]                   = { fg = col16.color05 },
        ["@parameter"]              = { fg = col16.color08 },
        ["@reference"]              = { fg = col16.color05 },
        ["@punctuation.bracket"]    = { fg = col16.color0F },
        ["@punctuation.delimiter"]  = { fg = col16.color0F },
        ["@punctuation.special"]    = { fg = col16.color08 },
        ["@string"]                 = { fg = col16.color0B },
        ["@string.regex"]           = { fg = col16.color0C },
        ["@string.escape"]          = { fg = col16.color0C },
        ["@string.special"]         = { fg = col16.color0C },
        ["@symbol"]                 = { fg = col16.color0B },
        ["@tag"]                    = { fg = col16.color0A },
        ["@tag.attribute"]          = { fg = col16.color08 },
        ["@tag.delimiter"]          = { fg = col16.color0F },
        ["@text"]                   = { fg = col16.color05 },
        ["@text.strong"]            = { bold = true },
        ["@text.emphasis"]          = { fg = col16.color09 },
        ["@text.strike"]            = { fg = col16.color0F, strikethrough = true },
        ["@text.literal"]           = { fg = col16.color09 },
        ["@text.uri"]               = { fg = col16.color09, underline = true },
        ["@type.builtin"]           = { fg = col16.color0A },
        ["@variable"]               = { fg = col16.color05 },
        ["@variable.builtin"]       = { fg = col16.color09 },
        ["@definition"]             = { sp = col16.color04, underline = true },
        ["@scope"]                  = { bold = true },
        ["@field"]                  = { fg = col16.color08 },
        ["@field.key"]              = { fg = col16.color08 },
        ["@property"]               = { fg = col16.color08 },
        ["@include"]                = { link = "Include" },
        ["@conditional"]            = { fg = col16.color0E },
        ["@conditional.ternary"]    = { fg = col16.color0E },
        ["@comment"]                = { fg = col30.grey_fg },
    }
end

return M
